### Series is ndarray-like

In [1]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series(np.random.rand(5), index=["a", "b", "c", "d", "e"])
s

a    0.064913
b    0.538521
c    0.889679
d    0.682595
e    0.535797
dtype: float64

In [4]:
s[0]

0.0649125423780087

In [5]:
s[:3]

a    0.064913
b    0.538521
c    0.889679
dtype: float64

In [8]:
s[[4, 3, 1]]

e    0.535797
d    0.682595
b    0.538521
dtype: float64

In [11]:
s[s > s.median()]

c    0.889679
d    0.682595
dtype: float64

In [12]:
np.exp(s)

a    1.067066
b    1.713470
c    2.434347
d    1.979006
e    1.708810
dtype: float64

In [13]:
s.dtype

dtype('float64')

In [14]:
s.array

<PandasArray>
[0.0649125423780087, 0.5385205709850134, 0.8896786464289272,
 0.6825948957547604, 0.5357970780880111]
Length: 5, dtype: float64

In [17]:
s.array[0:3]

<PandasArray>
[0.0649125423780087, 0.5385205709850134, 0.8896786464289272]
Length: 3, dtype: float64

In [23]:
# actual ndarray
s_np = s.to_numpy()
s_np

array([0.06491254, 0.53852057, 0.88967865, 0.6825949 , 0.53579708])

In [20]:
s_np[0]

0.0649125423780087

In [21]:
s_np[0:3]

array([0.06491254, 0.53852057, 0.88967865])

In [22]:
s_np[[0, 2, 4]]

array([0.06491254, 0.88967865, 0.53579708])