## Accessing/Changing elements, rows, cols

In [36]:
import numpy as np

In [16]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### Get specific elements

In [17]:
# Get specific element [r, c] ex. 13 element at second row
a[1, 5]

13

#### using negative notation

In [18]:
# Get specific element [r, c] ex. 13 element at second row
a[1, -2]

13

### Get specific row or col

In [19]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# Get specific col
a[:, 2]

array([ 3, 10])

### More staff with accessing and selecting [strtidx:endidx:step]

In [21]:
# selecting number in first row between 2 and 6
a[0, 1:6:2]

array([2, 4, 6])

In [22]:
# selecting number in first row between 2 and 6
a[0, 1:-1:2]

array([2, 4, 6])

### Changing elements

In [23]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
print(f'array before changing:\n{a}\n')
a[:, 2] = 5
print(f'array after changing:\n{a}')

array before changing:
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]

array after changing:
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


### Defining 3D array

In [25]:
mat = np.zeros((4, 3, 4))

In [26]:
mat

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [92]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [87]:
print(c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [42]:
c.ndim

3

In [43]:
c.shape

(2, 2, 2)

### Get specific element from 3D-Array

#### recomonded way (work outside in)

In [45]:
# Get 4 from 3D-Array named c (above)
c[0, 1, 1] # wich read like this: first array, second row, second col

4

In [106]:
c[:]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [108]:
c[:, 1, 1]

array([4, 8])

In [132]:
print(c[:, 0, 1:])

[[2]
 [6]]


In [144]:
c[:, 1, 0:]

array([5, 6])

In [146]:
c[:, 1, :]

array([[3, 4],
       [7, 8]])

In [176]:
c[1:, 0:, 1]

array([[6, 8]])

In [196]:
c[:, 0:, 0:1]

array([[[1],
        [3]],

       [[5],
        [7]]])

In [208]:
c[:, :, 0] = [[0, 0], [0, 0]]

In [209]:
c

array([[[0, 2],
        [0, 4]],

       [[0, 6],
        [0, 8]]])

In [211]:
c[:, :, 1]

array([[2, 4],
       [6, 8]])

In [218]:
c[:, 0, 1]

array([2, 6])