## Mathematics

### Math and Linalg Ref
[Math Routines](https://numpy.org/doc/stable/reference/routines.math.html)

[Linear Algebra Routines Ref.](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [1]:
import numpy as np

In [16]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


### Element wise op arithmetic

In [4]:
print(f'a: {a}')

a: [1 2 3 4]


In [17]:
# addition
print(f'a + 2 -> {a + 2}')

a + 2 -> [3 4 5 6]


In [6]:
# subtration
print(f'a - 2 -> {a - 2}')

a - 2 -> [-1  0  1  2]


In [18]:
# Mult
print(f'a * 2 -> {a * 2}')

a * 2 -> [2 4 6 8]


In [19]:
# Divsion
print(f'a / 2 -> {a / 2}')

a / 2 -> [0.5 1.  1.5 2. ]


### Arithmetic with arrays

In [20]:
b = np.array([1, 0, 1, 0])

In [21]:
b

array([1, 0, 1, 0])

In [23]:
a

array([1, 2, 3, 4])

In [24]:
a + b

array([2, 2, 4, 4])

In [26]:
a - b

array([0, 2, 2, 4])

In [27]:
a * b

array([1, 0, 3, 0])

In [29]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [33]:
# Take sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

In [35]:
x = np.ones((2, 3))
y = np.full((3, 2), 2)

In [36]:
print(x)
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [50]:
c = np.ones([9, 5, 4, 3])
m = np.ones([9, 5, 4, 3])

In [51]:
n = np.ones((9, 5, 4, 3))

In [52]:
m.shape == n.shape

True

In [47]:
(c==m).all()

True

In [53]:
np.array_equal(c, m)

True

In [60]:
%%timeit
(m == n).all()

14.9 µs ± 3.76 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [61]:
%%timeit
np.array_equal(m, n)

16.3 µs ± 308 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [66]:
np.matmul(x, y)

array([[6., 6.],
       [6., 6.]])

In [69]:
# finde determinant
d = np.identity(3)
np.linalg.det(d)

1.0

In [68]:
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Statistics

In [92]:
stats = np.array([[1, 5, 8], [4, 3, 6]])
print(stats)

[[1 5 8]
 [4 3 6]]


In [76]:
np.min(stats)

1

In [93]:
np.min(stats, axis=0)

array([1, 3, 6])

In [94]:
np.min(stats, axis=1)

array([1, 3])

In [95]:
np.max(stats)

8

In [103]:
np.max(stats, axis=0)

array([4, 5, 8])

In [97]:
np.max(stats, axis=1)

array([8, 6])

In [98]:
np.sum(stats)

27

In [100]:
print(stats)

[[1 5 8]
 [4 3 6]]


In [105]:
np.sum(stats, axis=1)

array([14, 13])

In [106]:
np.sum(stats, axis=0)

array([ 5,  8, 14])