In [2]:
import numpy as np

 ## initialize  different types of arrays

In [2]:
# All 0s matrix
# np.zeros((2, 3, 3))
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [3]:
# fill with other values
np.full((2, 3, 3), 99)

array([[[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99],
        [99, 99, 99]]])

In [5]:
a = np.array([[1,2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [6]:
# fill with full_like
np.full_like(a, 99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [7]:
# init with random dec values
np.random.rand(4, 2)

array([[0.52151267, 0.99395741],
       [0.46158514, 0.6777692 ],
       [0.14550924, 0.86010723],
       [0.98544992, 0.45549619]])

In [8]:
# init with random int values
np.random.randint(5, size=(2,2))

array([[4, 4],
       [1, 4]])

In [9]:
# repeating array
arr = np.array([[1, 2, 3]])
arr
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Question:
make the following array
1 1 1 1 1
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1

In [10]:
crzy = np.ones((5, 5), dtype='int32')
z = np.zeros((3, 3))
z[1, 1] = 9
# crzy[1:4, 1:4] = z
crzy[1:-1, 1:-1] = z

In [11]:
print(crzy)
print(z)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [17]:
# np.identity(2)
# np.identity(3)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
crzy = np.ones((5,5), dtype='int32')
z = np.zeros((3, 3), dtype='int32')
z[1, 1] = 9
crzy[1:-1, 1:-1] = z

In [31]:
crzy

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [29]:
z

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

### Be carfule with copying

In [43]:
x = np.array([1, 2, 3])
y = x.copy()
y[2] = 0
y
x

array([1, 2, 3])