## miscellaneous

### load data from file

In [1]:
import numpy as np

In [10]:
data = np.genfromtxt('data.txt', delimiter=',').astype('int32')

In [11]:
data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean and Advanced Indexing

In [51]:
# indexing based on list
a = np.random.randint(9, size=9)
print(a)
a[[0, 3, 7]]

[3 7 3 5 4 5 1 0 8]


array([3, 5, 0])

In [21]:
data > 50 # will return where in data values are greater than 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [68]:
print(data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [22]:
data[data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [66]:
np.any(data > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [67]:
np.any(data > 50, axis=1)

array([ True,  True,  True])

In [69]:
np.all(data > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [70]:
np.all(data > 50, axis=1)

array([False, False, False])

In [72]:
print(data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [71]:
(data > 50) & (data < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [73]:
~((data > 50) & (data < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [85]:
m = np.array(range(1, 31), ndmin=2)

In [113]:
quiz_mat = np.arange(1, 31).reshape(6, 5)

In [115]:
print(quiz_mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [117]:
sig = quiz_mat[2:4, 0:2]
print(sig)

[[11 12]
 [16 17]]


In [120]:
spots = quiz_mat[[0, 1, 2, 3], [1, 2, 3, 4]]
print(spots)

[ 2  8 14 20]


In [133]:
# chuncks = quiz_mat[0,-2:]
chuncks = quiz_mat[[0, 4, 5], -2:]
print(chuncks)

[[ 4  5]
 [24 25]
 [29 30]]
