# NumPy lib Intro

### load numpy lib

In [29]:
import numpy as np

### Initialize arrays 1D and 2D

In [30]:
# initialize 1d array
a = np.array([1, 2, 3])
print(a)
a

[1 2 3]


array([1, 2, 3])

In [31]:
# initialize 2d array
b = np.array([[.2, 1.3, 9.], [.5, 7.1, 6.]])
print(b)
b

[[0.2 1.3 9. ]
 [0.5 7.1 6. ]]


array([[0.2, 1.3, 9. ],
       [0.5, 7.1, 6. ]])

### Dimension, Shape, data type

In [32]:
# Get Dimension
a.ndim # -> 1
b.ndim

2

In [33]:
# Get shape of ndarrays
print(f'Shapr of a: {a.shape}')
print(f'Shapr of b: {b.shape}')

Shapr of a: (3,)
Shapr of b: (2, 3)


In [34]:
c = np.array([9, 8, 7], dtype='int16')

In [35]:
c

array([9, 8, 7], dtype=int16)

In [36]:
c.dtype

dtype('int16')

In [37]:
a.dtype

dtype('int32')

In [38]:
b.dtype

dtype('float64')

### itemsize attribute Return [int] the length of one array element in bytes

In [39]:
# Get size in byte for a where a is an array of int32 
a.itemsize


4

In [40]:
# Get size in bytes for b where b is an array of float64
b.itemsize

8

In [41]:
# Get size in bytes for c where c is an array of int16
c.itemsize

2

### Total size

In [42]:
# Get Total size
a.size * a.itemsize

12

In [43]:
# Get Total size
a.nbytes

12