### Reorganizing Arrays (reshape, vstack, hstack)

In [1]:
import numpy as np

## Reshape

In [8]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [9]:
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [20]:
after = before.reshape(8, 1)
print(after)
after = before.reshape(2,4)
print(after)
after = before.reshape(2, 2, 2)
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Virtical Stack Vstack

In [24]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
v3 = np.array([9, 10, 11, 12])
np.vstack([v1, v2, v3])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Horizantol Stack Hstack

In [39]:
h1 = np.ones((2,4))
h2 = np.zeros((2, 2))

In [40]:
np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])