In [1]:
import numpy as np

### Accessing and changing rank 1 ndarray

In [2]:
x = np.arange(1, 6)

In [3]:
print(x)

[1 2 3 4 5]


In [4]:
print('1st ele:', x[0])
print('2nd ele:', x[1])
print('5th ele:', x[4])

1st ele: 1
2nd ele: 2
5th ele: 5


In [5]:
print('1st ele:', x[-5])
print('1st ele:', x[-4])
print('1st ele:', x[-1])

1st ele: 1
1st ele: 2
1st ele: 5


In [6]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


### Accessing and changing rank 2 ndarray

In [7]:
y = np.arange(1, 10).reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# 1 2 9
print('element at (0, 0):', y[0, 0])
print('element at (0, 1):', y[0, 1])
print('element at (2, 2):', y[2, 2])

element at (0, 0): 1
element at (0, 1): 2
element at (2, 2): 9


In [9]:
y[0, 0] = 20
print(y)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


### Adding & Deleting elements

In [16]:
m = np.arange(1, 6)
print(m)

[1 2 3 4 5]


In [17]:
m = np.delete(m, [0, 4])
print(m)

[2 3 4]


In [31]:
n = np.arange(1, 10).reshape(3, 3)
print('Original array:\n', n)

w = np.delete(n, 0, axis=0)
print('\nnew array with first row deleted along axis=0\n',w)

q = np.delete(n, 1, axis=1)
print('\nnew aary with second col deleted along axis=1\n', q)

r = np.delete(n, [0, 2], axis=1)
print('\nnew array with 1st and 3rd cols deleted along with axis=1\n', r)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

new array with first row deleted along axis=0
 [[4 5 6]
 [7 8 9]]

new aary with second col deleted along axis=1
 [[1 3]
 [4 6]
 [7 9]]

new array with 1st and 3rd cols deleted along with axis=1
 [[2]
 [5]
 [8]]


### Append element array

In [33]:
v = np.arange(1, 6)
print(v)

[1 2 3 4 5]


In [35]:
v = np.append(v, 6)
print(v)

[1 2 3 4 5 6]


In [37]:
v = np.append(v, [7, 8])
print(v)

[1 2 3 4 5 6 7 8]


In [58]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
a = np.append(a, [[10, 11, 12]], axis=0)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [60]:
a = np.append(a, [[13], [14], [15], [16]], axis=1)
print(a)

[[ 1  2  3 13]
 [ 4  5  6 14]
 [ 7  8  9 15]
 [10 11 12 16]]


### Insert elements to nd-array

In [61]:
b = np.array([1, 2, 5, 6, 7])
print(b)

[1 2 5 6 7]


In [62]:
b = np.insert(b, 2, [3, 4])
print(b)

[1 2 3 4 5 6 7]


In [94]:
c = np.array([[1, 2, 3], [7, 8, 9]])
print(c)

[[1 2 3]
 [7 8 9]]


In [95]:
c = np.insert(c, 1, [4, 5, 6], axis=0)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [96]:
c = np.insert(c, 3, 0, axis=0)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]


In [97]:
c = np.insert(c, 0, [10, 11, 12, 13], axis=1)
print(c)

[[10  1  2  3]
 [11  4  5  6]
 [12  7  8  9]
 [13  0  0  0]]


In [98]:
c = np.insert(c, 4, 1, axis=1)
print(c)

[[10  1  2  3  1]
 [11  4  5  6  1]
 [12  7  8  9  1]
 [13  0  0  0  1]]


### Stacking: vstack, hstack

In [99]:
d = np.array([1, 2])
print(d)

[1 2]


In [100]:
e = np.array([[3, 4], [5, 6]])
print(e)

[[3 4]
 [5 6]]


In [106]:
f = np.vstack((d, e))
print(f)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
j = np.hstack((e, d.reshape(2, 1)))
print(j)

[[3 4 1]
 [5 6 2]]
