In [1]:
import numpy as np

### Arithmetic on rank 1 arrays

In [5]:
x = np.arange(1, 5)
y = np.arange(5, 9)
print(f'{x}\n{y}')

[1 2 3 4]
[5 6 7 8]


In [6]:
print(x + y)
print(np.add(x, y))

[ 6  8 10 12]
[ 6  8 10 12]


In [7]:
print(f'sub op:{x - y}')
print(f'sum function: {np.subtract(x, y)}')
print(f'multiply op:{x * y}')
print(f'multiply function: {np.multiply(x, y)}')
print(f'divide op:{x / y}')
print(f'multiply function: {np.divide(x, y)}')


sub op:[-4 -4 -4 -4]
sum function: [-4 -4 -4 -4]
multiply op:[ 5 12 21 32]
multiply function: [ 5 12 21 32]
divide op:[0.2        0.33333333 0.42857143 0.5       ]
multiply function: [0.2        0.33333333 0.42857143 0.5       ]


### Arithmetic on rank 2 nd-arrays

In [8]:
m = np.arange(1, 5).reshape(2, 2)
n = np.arange(5, 9).reshape(2, 2)
print(f'{m}\n######\n{n}')

[[1 2]
 [3 4]]
######
[[5 6]
 [7 8]]


In [9]:
print(f'sum op:{m + n}')
print(f'sum function: {np.add(m, n)}')
print(f'sub op:{m - n}')
print(f'sub function: {np.subtract(m, n)}')
print(f'multiply op:{m * n}')
print(f'multiply function: {np.multiply(m, n)}')
print(f'divide op:{m / n}')
print(f'multiply function: {np.divide(m, n)}')

sum op:[[ 6  8]
 [10 12]]
sum function: [[ 6  8]
 [10 12]]
sub op:[[-4 -4]
 [-4 -4]]
sub function: [[-4 -4]
 [-4 -4]]
multiply op:[[ 5 12]
 [21 32]]
multiply function: [[ 5 12]
 [21 32]]
divide op:[[0.2        0.33333333]
 [0.42857143 0.5       ]]
multiply function: [[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Apply math function to all of the elements array

In [10]:
print(x)

[1 2 3 4]


In [11]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [12]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [13]:
print(np.power(x, 2))

[ 1  4  9 16]


### Apply Statisticals ops to an array

In [14]:
print(m)

[[1 2]
 [3 4]]


In [17]:
print(f'Avarage of all: {m.mean()}')

Avarage of all: 2.5


In [20]:
print(f'Avarage of columns: {m.mean(axis=0)}')
print(f'Avarage of rows: {m.mean(axis=1)}')

Avarage of columns: [2. 3.]
Avarage of rows: [1.5 3.5]


In [23]:
print(f'sum of all: {m.sum()}')
print(f'sum of columns: {m.sum(axis=0)}')
print(f'sum of rows: {m.sum(axis=1)}')

sum of all: 10
sum of columns: [4 6]
sum of rows: [3 7]


In [27]:
print(f'std of m: {m.std()}')
print(f'median of m: {np.median(m)}')
print(f'max of m: {m.max()}')
print(f'min of m: {m.min()}')

std of m: 1.118033988749895
median of m: 2.5
max of m: 4
min of m: 1


### Broadcasting

In [28]:
print(m)

[[1 2]
 [3 4]]


In [30]:
print(m + 3)
print(m - 3)
print(m * 3)
print(m / 3)

[[4 5]
 [6 7]]
[[-2 -1]
 [ 0  1]]
[[ 3  6]
 [ 9 12]]
[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [49]:
w = np.arange(9).reshape(3, 3)
v = np.arange(3)
z = np.arange(3).reshape(3, 1)
print(w)
print('####')
print(v,)
print('####')
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
####
[0 1 2]
####
[[0]
 [1]
 [2]]


In [50]:
print(w + v)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [51]:
print(np.add(w, v))

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [52]:
print(w + z)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [58]:
a = np.arange(5).reshape(5, 1)
b = np.arange(6).reshape(1, 6)
c = np.arange(6)
d = np.array(2)
print(a)
print(b)
print(c)
print(d)

[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4 5]]
[0 1 2 3 4 5]
2


In [59]:
a[:, 0]

array([0, 1, 2, 3, 4])

In [60]:
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [62]:
b[0, :]

array([0, 1, 2, 3, 4, 5])

In [63]:
a = np.array([0.0, 10.0, 20.0, 30.0])

b = np.array([1.0, 2.0, 3.0])

In [71]:
a[:]

array([ 0., 10., 20., 30.])

In [70]:
a[:, np.newaxis]

array([[ 0.],
       [10.],
       [20.],
       [30.]])