### Boolean indexing

In [1]:
import numpy as np

In [2]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [26]:
# indexing elements under certain creteria
target = x[x > 10]
print(target)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [24]:
# Get indices of targeted elements
r, c = np.where(x > 10)
for i, j in zip(r, c):
    print (f'x[{i}, {j}]')

x[2, 1]
x[2, 2]
x[2, 3]
x[2, 4]
x[3, 0]
x[3, 1]
x[3, 2]
x[3, 3]
x[3, 4]
x[4, 0]
x[4, 1]
x[4, 2]
x[4, 3]
x[4, 4]


In [27]:
print(x[x <= 7])

[0 1 2 3 4 5 6 7]


In [34]:
t = x[(x > 10) & (x < 17)]
print(t)

[11 12 13 14 15 16]


### Assigning to elements using Boolean indexing

In [41]:
y = x.copy()
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [42]:
y[(y > 10) & (y < 17)] = -1
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


### Set Operations

In [53]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 2, 8, 4])

print('Common elements (intersection):', np.intersect1d(a, b))
print('diff  elements (setdiff):', np.setdiff1d(a, b))
print('Union :', np.union1d(a, b))

Common elements (intersection): [2 4]
diff  elements (setdiff): [1 3 5]
Union : [1 2 3 4 5 6 7 8]


### Sorting

### Notes
    np.sort function sort out of place
    arr.sort method sort in place

In [55]:
m = np.random.randint(1, 11, size=(10,))
print(m)

[10  2  4 10  4  9  8 10  9  7]


### Sorting out of place

In [87]:
print('original:', m)
print('copy after sort:', np.sort(m))
print('copy after sort with uniques:', np.sort(np.unique(m)))
print('original after sort:', m)

original: [10  2  4 10  4  9  8 10  9  7]
copy after sort: [ 2  4  4  7  8  9  9 10 10 10]
copy after sort with uniques: [ 2  4  7  8  9 10]
original after sort: [10  2  4 10  4  9  8 10  9  7]


### Sorting in place

In [93]:
print('sorting: .....', m.sort())
print('original:', m)
print('original after sort with unique:', np.unique(m))
print()

sorting: ..... None
original: [ 2  4  4  7  8  9  9 10 10 10]
original after sort with unique: [ 2  4  7  8  9 10]



In [115]:
f = np.random.randint(1,11,size=(10,))
print(f)

[ 7  9  6  5  2 10  6  2  7  9]


In [117]:
# Sort by np.unique
print(np.unique(f))

[ 2  5  6  7  9 10]


### Sortin rank 2 nd-array

In [110]:
n = np.random.randint(1, 11, size=(5, 5))
print(n)

[[ 3  5  7  6 10]
 [ 7  7  5  6  8]
 [ 3  3  5 10  6]
 [ 1 10  8  4  4]
 [10  9  8  9  3]]


In [111]:
print(np.sort(n, axis=0))

[[ 1  3  5  4  3]
 [ 3  5  5  6  4]
 [ 3  7  7  6  6]
 [ 7  9  8  9  8]
 [10 10  8 10 10]]


In [112]:
print(np.sort(n, axis=1))

[[ 3  5  6  7 10]
 [ 5  6  7  7  8]
 [ 3  3  5  6 10]
 [ 1  4  4  8 10]
 [ 3  8  9  9 10]]
