In [1]:
import numpy as np

### Creating and explore arrays in NumPy

In [3]:
x = np.array([1, 2, 3, 4, 5])

In [5]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# type of ndarray elements
x.dtype

dtype('int32')

In [8]:
# shape of the ndarray
x.shape

(5,)

In [29]:
x.ndim

1

In [67]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [74]:
print(f'Y =\n {y}\n')
print('Y has dimensions:', y.shape)
print('Y has a total of', y.size, 'elements')
print('Y is an object of:', type(y))
print('Y elements of type:', y.dtype)

Y =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of: <class 'numpy.ndarray'>
Y elements of type: int32


In [30]:
y.ndim

2

In [12]:
y.dtype

dtype('int32')

In [13]:
y.shape

(4, 3)

In [16]:
y.size

12

In [17]:
y.itemsize

4

In [44]:
z = np.zeros((2, 3, 4))

In [45]:
print(z)
print(z.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


In [46]:
z.shape

(2, 3, 4)

In [51]:
z.shape = (3, 8)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [62]:
np.shape(z)
np.shape(np.eye(4))

(4, 4)

In [18]:
t = np.array(['Hello', 'World'])
print(t)

['Hello' 'World']


In [19]:
print(f'Shape: {t.shape}')
print(f'Type: {type(t)}')
print(f'dtype: {t.dtype}')

Shape: (2,)
Type: <class 'numpy.ndarray'>
dtype: <U5


In [20]:
tt = np.array([1, 2, 'World'])
print(f'Shape: {tt.shape}')
print(f'Type: {type(tt)}')
print(f'dtype: {tt.dtype}')

Shape: (3,)
Type: <class 'numpy.ndarray'>
dtype: <U11


In [21]:
mix_num = np.array([1, 2.5, 4])

In [23]:
print(mix_num)
print(mix_num.dtype)

[1.  2.5 4. ]
float64


In [26]:
a = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(a)

[1 2 3]


### Saving, and loaded data from numpy to a file

In [27]:
np.save('my_array', x)

In [28]:
loaded_file = np.load('my_array.npy')
print(loaded_file)

[1 2 3 4 5]


In [66]:
i = np.array([1, 2, 3], dtype=np.float64)
print(i)

[1. 2. 3.]
