    ```Use Broadcasting to create a 4 x 4 ndarray that has its firstcolumn full of 1s, its second column full of 2s, its third column full of 3s, etc.. 

    Do not change the name of this array. 
    Please don't print anything from your code! The TEST RUN button below will print your array.```

In [1]:
import numpy as np

In [18]:
x = np.ones((4, 4)) * np.arange(1, 5)
print(x)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
