In [1]:
import numpy as np

In [2]:
arr_2d = np.arange(0, 6).reshape([2, 3])
print(arr_2d)

[[0 1 2]
 [3 4 5]]


In [6]:
print('sum')
print(np.sum(arr_2d, axis=0))

sum
[3 5 7]


In [7]:
print(np.sum(arr_2d, axis=1))

[ 3 12]


In [8]:
np_array_1s = np.array([[1,1,1],[1,1,1]])
np_array_9s = np.array([[9,9,9],[9,9,9]])

In [9]:
print(np_array_1s)

[[1 1 1]
 [1 1 1]]


In [10]:
print(np_array_9s)

[[9 9 9]
 [9 9 9]]


In [13]:
np.concatenate((np_array_1s, np_array_9s), axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [14]:
np.concatenate((np_array_1s, np_array_9s), axis=1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [16]:
np_array_0s = np.zeros((2, 4))
print(np_array_0s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
np.concatenate((np_array_1s, np_array_0s), axis=1)

array([[1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]])

In [22]:
np_array_1s_1dim = np.array([1,1,1])
np_array_9s_1dim = np.array([9,9,9])

In [25]:
print(np_array_1s_1dim)
print('#######')
print(np_array_9s_1dim)

[1 1 1]
#######
[9 9 9]


In [29]:
np.concatenate((np_array_1s_1dim, np_array_9s_1dim), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1