In [1]:
import numpy as np

## slicing rank 2 ndarrays

### slicing sub-array from ndarray

In [64]:
m = np.arange(1, 21).reshape(4, 5)
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [65]:
# sub_m = m[1:4, 2:5]
sun_m = m[1:, 2:]
print(sub_m)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [66]:
sub_m2 = m[:3, 2:]
print(sub_m2)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


### select elements in rows and cols

In [67]:
# select all elements in 3rd col
print(m, '\n')
e_3rd_col = m[:, 2]
print(e_3rd_row)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[ 3  8 13 18]


In [68]:
# selec 3rd col and return it as rank 2 array
print(m,'\n')
r_col = m[:, 2:3]
print(r_col)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[ 3]
 [ 8]
 [13]
 [18]]


In [69]:
# select all elements in 2nd row
print(m,'\n')
e_2nd_row = m[1]
print(e_2nd_row)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[ 6  7  8  9 10]


In [70]:
# selec 2nd row and return it as rank 2 array
print(m,'\n')
e_2nd_row = m[1:2]
print(e_2nd_row)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[ 6  7  8  9 10]]


### slicing as views and slicing and copies

In [71]:
n = np.arange(1, 21).reshape(4, 5)
print(n, '\n')
z = n[1:, 2:]
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [72]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [74]:
print(n)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [77]:
z1 = np.copy(m[1:, 2:])
print(z1, '\n')
z1[2, 2] = 555

[[ 8  9 10]
 [13 14 15]
 [18 19 20]] 



In [78]:
print(m, '\n')
print(z1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [79]:
z2 = m[1:, 2:].copy()
print(z2)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [81]:
z2[2, 2] = 555
print(m, '\n')
print(z2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


### select and slicing using array from another nd-array

In [82]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [83]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [88]:
y = x[indices, :].copy()
print(y)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [89]:
z = x[:, indices]
print(z)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


### diagonals

In [92]:
w = np.arange(20).reshape(4, 5)
print(w)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [96]:
# main diagonal
# dia = w.diagonal() # also work
dia = np.diag(w)
print(dia)

[ 0  6 12 18]


In [104]:
# below main diagona
dia_b = np.diag(w, k=-1)
print(dia_b)

[ 5 11 17]


In [107]:
# above main diagona
# dia_a = w.diagonal(1)
dia_a = np.diag(w, k=1)
print(dia_a)

[ 1  7 13 19]


### unique

In [108]:
arr = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
print(arr)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [122]:
u = np.unique(arr)
print(u)

# return_index=False,
# return_inverse=False,
# return_counts=False,
# axis=None,

[1 2 3 5 8]
