In [1]:
import numpy as np

In [3]:
# create ndarray of zeros
z = np.zeros((3, 4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# create ndarray of ones
x = np.ones((4, 5), dtype=int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [9]:
# create an array filled with constants values
y = np.full((3, 4), 5)
print(y)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create identity matrix using eye func
ide = np.eye(5)
print(ide)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# create a diagonal matrix
d = np.diag([10, 20, 30, 40, 50])
print(d)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [17]:
# Generate a rank 1 array with arange func
gen = np.arange(1, 20, 2)
print(gen)

[ 1  3  5  7  9 11 13 15 17 19]


In [18]:
# Generate a rank 1 array its element evenly spaced with linspace
lin = np.linspace(0, 25, 10)
print(lin)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [30]:
# Generate a rank 1 array its element evenly spaced with linspace
lin = np.linspace(0, 25, 10, endpoint=False)
print(lin)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [32]:
# Create rank 2 array with arange and reshape 
m = np.arange(1, 21)
print(m)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [35]:
mat = np.reshape(m, (4, 5))

In [36]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
mat2 = np.reshape(m, (2, 10))
# mat2 = np.reshape(m, (10, 2))
print(mat2)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [45]:
# extra exa
r_mat = np.arange(1, 21).reshape(4, 5)
print(r_mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [47]:
lins = np.linspace(0, 25, 10, endpoint=False).reshape(5, 2)

print(lins)

[[ 0.   2.5]
 [ 5.   7.5]
 [10.  12.5]
 [15.  17.5]
 [20.  22.5]]


In [52]:
# create ndarray filled with random float in range [0.0, 1.0)
ran_mat = np.random.random((3, 3))
print(ran_mat)

[[0.34969245 0.97631797 0.45829604]
 [0.76251253 0.94466364 0.46831382]
 [0.65010254 0.65831991 0.45862943]]


In [55]:
# create random ndarray with random.randint
int_mat = np.random.randint(5, 16, (3, 3))
print(int_mat)

[[11 11  6]
 [ 9 14 13]
 [10  5  9]]


In [65]:
# create rank 2 array with random.normal
n = np.random.normal(0, 0.1, (1000, 1000))
print(n)

[[ 0.1461221  -0.12599155  0.07410877 ... -0.13765832  0.03208659
  -0.03781071]
 [ 0.02141487  0.15961039 -0.09703337 ...  0.14707449 -0.02063653
  -0.21305615]
 [ 0.03276387  0.04923444 -0.01735113 ... -0.0981331  -0.10148682
   0.05893727]
 ...
 [ 0.00301056  0.0703776  -0.09717976 ... -0.02724844 -0.11464288
   0.06981614]
 [-0.19642874 -0.15191478 -0.18404365 ... -0.00284964 -0.14589323
   0.00992575]
 [ 0.09721531 -0.0092672  -0.04526228 ... -0.09615498  0.22560753
  -0.04335931]]


In [66]:
print('mean:', n.mean())
print('std:', n.std())
print('max:', n.max())
print('min:', n.min())
print('# positive:', (x > 0).sum())
print('# negative:', (x < 0).sum())

mean: -0.00025422127382242546
std: 0.10005370283721256
max: 0.5050137179102612
min: -0.4607838854856614
# positive: 20
# negative: 0


In [77]:
w = np.arange(10, 20)
print(w)
print(w.dtype)

[10 11 12 13 14 15 16 17 18 19]
int32


In [78]:
w.shape, w.ndim, w.size, w.itemsize

((10,), 1, 10, 4)

In [80]:
w.reshape(2, 5)
w

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])